# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://zacharyshaleweiss.com
title: ZSWPortfolio
email: zweiss@brandeis.edu
author: Zachary Shale Weiss
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2015 Zachary S. Weiss. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:

  - icon: envelope-o
    title: envelope-o
    url: mailto:zweiss@brandeis.edu
  - title: linkedin
    url: https://www.linkedin.com/in/zacharyshaleweiss
  - title: github
    url: https://github.com/ZachsHacks
  - title: Resumé
    url: https://drive.google.com/open?id=0Bx5GB26OrXWiSjIyYUFwQ2l2emM
