# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://zacharyshaleweiss.com
title: ZSW Portfolio
email: info@zacharyshaleweiss.com
author: Zachary S. Weiss
description: > # "Zachary Shale Weiss's Personal Website"

copyright: 'Copyright &copy; 2016 Zachary Weiss. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: envelope-o
    title: email
    url: mailto:info@zacharyshaleweiss.com
  - title: github
    url: https://github.com/ZachsHacks
  - title: linkedin
    url: https://www.linkedin.com/in/zacharyshaleweiss
  - icon: file-pdf-o
    title: resume
    url: https://drive.google.com/file/d/0Bx5GB26OrXWiSjIyYUFwQ2l2emM/view?usp=sharing
